---
layout: cv
title: Victor Affleck's CV
---
# Victor Affleck
Student, writer, flexible worker, potential tech worker




## Currently

Trying to graduate BYU-I 

### Specialized in

Attention to detail. Finding patterns. Working until the job is done. 


### Research interests

Coding. Fiction. Large Software 


## Education

`2011-2015`
__Hillcrest High School, Idaho__

-honors student 

`2018-2020`
__Utah State University, Utah__


`2023-current`
__Brigham Young University, Idaho__





## Awards

`2015`
- Eagle scout award 

`2015-2017`
- Full time, 2 year, religious mission for the Church of Jesus Christ of Latter-Day Saints (LDS)



## Accomplishments 
-  Organized and ran a 4 week VEX Robotics and Lego Mindstorms camp for 10-14 year olds. 
- Remodeled 2 medical offices. 
- Personally counted and inventoried approx. 8,000 items of clean room laundry for downsizing. 


## Occupation

`2011-2015`
__Affleck Eye Care__, Idaho, Idaho Falls

- Receptionsit
- Document Transfer Manager
- 

`2019-2020`
__Heritage Glass__, Logan, Utah

 - Glass recylcer and smelter

 `2020`
 __Utah State University College of Agriculture__, Logan, Utah

 - Weed Technition

 `2021-2023` 
 __Entegris, Flex Concepts__, Logan, Utah

 - Line assembly operator 
 - Shipping and Boxing


<!-- ### Footer

Last updated: March 2024 -->